import { $ } from "bun";
import { tmpdir, homedir } from "os";
import { join } from "path";
import { existsSync, readFileSync } from "fs";
import { randomBytes } from "crypto";
import Cloudflare from "cloudflare";
import packageJson from "../package.json";

// Configuration - set your custom domain here
const CUSTOM_DOMAIN = "myapp.example.com"; // e.g., "myapp.example.com"

if (!CUSTOM_DOMAIN) {
    console.error("❌ CUSTOM_DOMAIN must be set in ./infra/deploy.ts");
    process.exit(1);
}

// Resolve paths
const infraDir = import.meta.dir;
const rootDir = join(infraDir, "..");
const stateFilePath = join(infraDir, "deploy-state.ts");
const APP_NAME = packageJson.name;

/**
 * Get Cloudflare API token from environment or wrangler config
 * Wrangler stores OAuth tokens at:
 * - macOS: ~/Library/Preferences/.wrangler/config/default.toml
 * - Linux/Windows: ~/.wrangler/config/default.toml
 */
async function getCloudflareToken(): Promise<string | undefined> {
    // First check environment variable
    if (process.env.CLOUDFLARE_API_TOKEN) {
        return process.env.CLOUDFLARE_API_TOKEN;
    }

    // Run a lightweight wrangler command to trigger OAuth token refresh if needed
    // wrangler automatically refreshes expired tokens
    try {
        await $`wrangler whoami`.quiet();
    } catch {
        // Ignore errors - user might not be logged in
    }

    // Read from wrangler config (same location wrangler login uses)
    const wranglerConfigPaths = [
        join(homedir(), "Library/Preferences/.wrangler/config/default.toml"), // macOS
        join(homedir(), ".wrangler/config/default.toml"), // Linux/Windows
    ];

    for (const configPath of wranglerConfigPaths) {
        if (existsSync(configPath)) {
            try {
                const content = readFileSync(configPath, "utf-8");
                const match = content.match(/oauth_token\s*=\s*"([^"]+)"/);
                if (match) {
                    return match[1];
                }
            } catch {
                // Continue to next path
            }
        }
    }

    return undefined;
}

interface DeployState {
    databaseId: string;
    databaseName: string;
    authSecret: string;
}

async function loadOrCreateState(): Promise<DeployState> {
    const databaseName = `${APP_NAME}-db`;

    // Check if state file exists
    if (existsSync(stateFilePath)) {
        const state = await import(stateFilePath);
        console.log(`✅ Using existing database: ${state.databaseName}`);

        // Migration: add authSecret if missing from older state files
        if (!state.authSecret) {
            const authSecret = randomBytes(32).toString("base64");
            console.log(`✅ Generated auth secret (migration)`);

            const stateContent = `// Auto-generated by deploy.ts - do not edit manually
export const databaseId = "${state.databaseId}";
export const databaseName = "${state.databaseName}";
export const authSecret = "${authSecret}";
`;
            await Bun.write(stateFilePath, stateContent);
            return { ...state, authSecret };
        }

        return state;
    }

    // Get token from env or wrangler config (triggers refresh if needed)
    const apiToken = await getCloudflareToken();

    if (!apiToken) {
        console.error("❌ No Cloudflare credentials found.");
        console.error("   Run 'wrangler login' or set CLOUDFLARE_API_TOKEN");
        process.exit(1);
    }

    // Use Cloudflare SDK
    console.log("🔄 Creating D1 database via Cloudflare API...");
    const cf = new Cloudflare({ apiToken });

    const accounts = await cf.accounts.list();
    const accountId = accounts.result?.[0]?.id;
    if (!accountId) {
        throw new Error("No Cloudflare account found");
    }

    const database = await cf.d1.database.create({
        account_id: accountId,
        name: databaseName,
    });

    const databaseId = database.uuid;
    if (!databaseId) {
        throw new Error("Failed to create D1 database - no UUID returned");
    }
    console.log(`✅ Created database with ID: ${databaseId}`);

    // Generate a secure random auth secret
    const authSecret = randomBytes(32).toString("base64");
    console.log(`✅ Generated auth secret`);

    const stateContent = `// Auto-generated by deploy.ts - do not edit manually
export const databaseId = "${databaseId}";
export const databaseName = "${databaseName}";
export const authSecret = "${authSecret}";
`;
    await Bun.write(stateFilePath, stateContent);
    console.log(`✅ Saved state to deploy-state.ts`);

    return { databaseId, databaseName, authSecret };
}

async function deploy() {
    // Load or create database and secrets
    const { databaseId, databaseName, authSecret } = await loadOrCreateState();

    // Configuration
    const config = {
        database: {
            name: databaseName,
            id: databaseId,
        },
        worker: {
            name: APP_NAME,
            customDomain: CUSTOM_DOMAIN,
        },
        schema: join(rootDir, "auth/db-schema.ts"),
        migrations: join(infraDir, "migrations"),
    };

    // Generate wrangler config with absolute paths
    const wranglerConfig = {
        $schema: "node_modules/wrangler/config-schema.json",
        name: config.worker.name,
        main: join(infraDir, "index.ts"),
        compatibility_date: "2024-12-01",
        compatibility_flags: ["nodejs_compat"],
        build: {
            command: `bun build ${join(rootDir, "frontend/index.html")} --outdir=${join(rootDir, "dist")} --sourcemap --target=browser --minify --define:process.env.NODE_ENV='"production"'`,
        },
        assets: {
            directory: join(rootDir, "dist"),
            binding: "ASSETS",
            not_found_handling: "single-page-application",
        },
        d1_databases: [
            {
                binding: "DB",
                database_name: config.database.name,
                database_id: config.database.id,
                migrations_dir: config.migrations,
            },
        ],
        routes: [
            {
                pattern: CUSTOM_DOMAIN,
                custom_domain: true,
            },
        ],
        observability: {
            logs: {
                enabled: true,
                head_sampling_rate: 1,
                invocation_logs: true,
            },
        },
    };

    // Write wrangler config to temp file
    const configPath = join(tmpdir(), "wrangler.json");
    await Bun.write(configPath, JSON.stringify(wranglerConfig, null, 2));

    console.log("🔄 Generating migrations from schema...");
    await $`drizzle-kit generate --dialect=sqlite --schema=${config.schema} --out=${config.migrations}`;

    console.log("🔄 Applying migrations to D1...");
    await $`wrangler d1 migrations apply ${config.database.name} --remote --config=${configPath}`;

    console.log("🚀 Deploying worker...");
    await $`wrangler deploy --config=${configPath}`;

    // Upload secrets to the worker (pipe secret value to wrangler)
    console.log("🔐 Uploading secrets...");
    const secretProc = Bun.spawn(["wrangler", "secret", "put", "BETTER_AUTH_SECRET", "--config", configPath], {
        stdin: "pipe",
        stdout: "inherit",
        stderr: "inherit",
    });
    secretProc.stdin.write(authSecret);
    secretProc.stdin.end();
    await secretProc.exited;
    console.log("✅ Secrets uploaded");

    console.log("✅ Deployment complete!");
}

deploy().catch((err) => {
    console.error("❌ Deployment failed:", err);
    process.exit(1);
});

